### ISSUE TITLE
About My Rank

### ISSUE THREAD

**Issue by Sn-Kinos** [jaemuon/jaemuon.github.com#2]
![image](https://user-images.githubusercontent.com/26380261/33354528-ac6c5104-d4f6-11e7-86d0-b4ae17c57d21.png)

My level and pp isn't show on page.

Please fix it

**Comment by iknowSteven** [comment]
It beacuse your rank is so low that web worker do not provide your stat.

**Comment by Sn-Kinos** [comment]
@iknowSteven Ah, I played this game just 4 times.
I understand
